version: '3.8'

services:
  skyreels-unlimited:
    build:
      context: .
      dockerfile: Dockerfile.unlimited
    image: skyreels-v2:unlimited
    container_name: skyreels-unlimited
    restart: unless-stopped
    
    # GPU配置
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    # 端口映射
    ports:
      - "8000:8000"
    
    # 环境变量 - 无限制配置
    environment:
      # 核心无限制设置
      - SKYREELS_UNLIMITED_MODE=true
      - SKYREELS_MAX_RESOLUTION=1080p
      - SKYREELS_MAX_DURATION=7200  # 2小时
      - SKYREELS_ENABLE_4K=true
      - SKYREELS_HIGH_QUALITY=true
      
      # GPU优化
      - CUDA_VISIBLE_DEVICES=0
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:4096
      - TORCH_BACKENDS_CUDNN_BENCHMARK=true
      - TORCH_BACKENDS_CUDA_MATMUL_ALLOW_TF32=true
      - TORCH_BACKENDS_CUDNN_ALLOW_TF32=true
      
      # 性能调优
      - OMP_NUM_THREADS=16
      - MKL_NUM_THREADS=16
      - NUMBA_NUM_THREADS=16
      - TORCH_NUM_THREADS=16
      
      # 内存管理
      - PYTHONUNBUFFERED=1
      - TOKENIZERS_PARALLELISM=false
      - PYTHONHASHSEED=0
      
      # 缓存目录
      - HF_HOME=/app/cache
      - TRANSFORMERS_CACHE=/app/cache
      - TORCH_HOME=/app/cache
      - HUGGINGFACE_HUB_CACHE=/app/cache
    
    # 卷挂载
    volumes:
      - ./outputs:/app/outputs           # 输出文件
      - ./cache:/app/cache               # 模型缓存
      - ./logs:/app/logs                 # 日志文件
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # X11支持（可选）
    
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # 共享内存大小（大模型需要）
    shm_size: '2gb'
    
    # 网络模式
    network_mode: bridge

# 可选：创建专用网络
networks:
  default:
    driver: bridge

# 可选：创建命名卷
volumes:
  skyreels_cache:
    driver: local
  skyreels_outputs:
    driver: local
  skyreels_logs:
    driver: local 